x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}

x-airflow-volumes: &airflow-volumes
  - ./dags:/opt/airflow/dags
  - ./logs:/opt/airflow/logs
  - ./src:/opt/airflow/src

services:
  trading-airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      <<: *airflow-env
    entrypoint:
      - /bin/bash
      - -c
      - |
        airflow db upgrade &&
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com
    volumes: *airflow-volumes
    restart: "no"

  trading-airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: webserver
    restart: always
    depends_on:
      - trading-airflow-init
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-env
    volumes: *airflow-volumes

  trading-airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: scheduler
    restart: always
    depends_on:
      - trading-airflow-webserver
    environment:
      <<: *airflow-env
    volumes: *airflow-volumes
    ports:
      - "8793:8793"
