name: Deploy Airflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy Airflow
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_AIRFLOW_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/airflow-repo
            git pull origin main
            docker-compose down
            docker-compose up -d --build
